import Head from 'next/head'
import Image from 'next/image'
import NextLink from 'next/link'
import React, { useState } from 'react'
import styles from '../styles/Home.module.css'
import api from '../helpers/api'

export default function Login() {
  const [email, setEmail] = useState('')

  const handleSubmit = (e: React.SyntheticEvent) => {
    e.preventDefault()
    api.post('forgot-password', { email: email }).then(res => console.log('res : ' + JSON.stringify(res))).catch(e => console.log('e : ' + e))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Forgot password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Forgot password
        </h1>

        <p className={styles.description}>
          <NextLink href="/">Home</NextLink>
        </p>

        <div className={styles.grid}>
          <form onSubmit={handleSubmit}>
            <div>
              <label>Email</label>
              <input type="email" name="email" onChange={(e: React.ChangeEvent<HTMLInputElement>) => setEmail(e.target.value)} />
            </div>
            <input type="submit" />
          </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
