import Head from 'next/head'
import React, { useRef, useState } from 'react'
import api from '../helpers/api'
import { InputText } from 'primereact/inputtext'
import { Card } from 'primereact/card';
import { Button } from 'primereact/button';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from "yup";
import { Toast } from 'primereact/toast';

type ForgotPasswordData = {
  email: string;
}

const schema = yup.object().shape({
  email: yup.string().email().max(255).required()
});

export default function Login() {
  const [loading, setLoading] = useState(false)
  const toast = useRef<Toast>(null);
  const { register, handleSubmit, formState: { errors } } = useForm({
    resolver: yupResolver(schema)
  })

  const onSubmit = (data: ForgotPasswordData) => {
    setLoading(true)
    api.post('forgot-password', data).then(res => {
      setLoading(false)
      return toast.current?.show({ severity: 'success', summary: 'Success Message', detail: res.data.data })
    }).catch(e => {
      setLoading(false)
      const { error, data, errors } = e.response.data
      if (error) {
        return toast.current?.show({ severity: 'error', summary: 'Error Message', detail: data })
      }
      if (errors) {
        const allErrors = Object.keys(errors).map(key => errors[key]).flat()
        return allErrors.forEach(error => toast.current?.show({ severity: 'error', summary: 'Error Message', detail: error }))
      }

      return toast.current?.show({ severity: 'error', summary: 'Error Message', detail: 'Something went wrong!' })
    })
  }

  const getFormErrorMessage = (name: string) => {
    return errors[name] && <small className="p-error">{errors[name].message}</small>
  };

  return (
    <div className="d-flex flex-grow-1">
      <Head>
        <title>Forgot password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container d-flex flex-grow-1 mb-3">
        <div className="row flex-grow-1 justify-content-center align-items-center">
          <Card title='Forgot password' className="col-12 col-md-9 col-lg-6 col-xl-4">
            <form onSubmit={handleSubmit(onSubmit)} className="p-fluid">
              <div className="p-field p-mb-5">
                <label htmlFor="email">Email</label>
                <InputText id="email" type="email" {...register("email")} />
                {getFormErrorMessage('email')}
              </div>
              <Button label="Send" iconPos="right" loading={loading} />
            </form>
          </Card>
        </div>
        <Toast ref={toast} />
      </main>
    </div>
  )
}
