import Head from 'next/head'
import NextLink from 'next/link'
import React, { FC, useState } from 'react'
import api from '../helpers/api'
import { logIn, logOut } from '../helpers/auth'
import { InputText } from 'primereact/inputtext'
import { Card } from 'primereact/card'
import { Button } from 'primereact/button'
import { useForm } from 'react-hook-form'
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from "yup";

type LoginData = {
  email: string;
  password: string;
}

const schema = yup.object().shape({
  email: yup.string().email().max(255).required(),
  password: yup.string().min(12).required()
});

export default function Login() {
  const [loading, setLoading] = useState(false)
  const { register, handleSubmit, formState: { errors } } = useForm({
    resolver: yupResolver(schema)
  })

  const onSubmit = (data: LoginData) => {
    setLoading(true)
    api.get('csrf-cookie').then(() => {
      api.post('login', data).then(res => logIn()).catch(e => logOut())
    })
  }

  const LoginCardFooter: FC = () => {
    return (
      <div className="p-field p-d-flex p-jc-center">
        <NextLink href="/register">Don't have an account?</NextLink>
      </div>
    )
  }

  const getFormErrorMessage = (name: string) => {
    return errors[name] && <small className="p-error">{errors[name].message}</small>
  };

  return (
    <div className="container mx-auto px-4 flex flex-col justify-center h-screen">
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto md:w-96">
        <Card title='Login' footer={LoginCardFooter}>
          <form onSubmit={handleSubmit(onSubmit)} className="p-fluid">
            <div className="p-field">
              <label htmlFor="email">Email</label>
              <InputText id="email" type="email" {...register("email")} />
              {getFormErrorMessage('email')}
            </div>
            <div className="p-field">
              <label htmlFor="password">Password</label>
              <InputText id="password" type="password" {...register("password")} />
              {getFormErrorMessage('password')}
            </div>
            <div className="p-field p-d-flex p-jc-center p-mb-5">
              <NextLink href="/forgot-password">Forgot password?</NextLink>
            </div>
            <Button label="Log in" iconPos="right" loading={loading} />
          </form>
        </Card>
      </main>
    </div>
  )
}
