import Head from 'next/head'
import React, { useRef, useState } from 'react'
import api from '../helpers/api'
import { useRouter } from 'next/router'
import { InputText } from 'primereact/inputtext'
import { Card } from 'primereact/card';
import { Button } from 'primereact/button';
import { useForm } from 'react-hook-form'
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from "yup";
import { Toast } from 'primereact/toast'

type ResetPasswordData = {
  email: string;
  password: string;
  password_confirmation: string;
}

const schema = yup.object().shape({
  email: yup.string().email().max(255).required(),
  password: yup.string().min(12).required().matches(
    /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]/,
    "Password must contain at least one uppercase, one lowercase, one number and one special case character"
  ),
  password_confirmation: yup.string().oneOf([yup.ref('password'), null], "Password confirmation doesn't match")
});

export default function ResetPassword() {
  const { query: { token } } = useRouter()
  const [loading, setLoading] = useState(false)
  const toast = useRef<Toast>(null);
  const { register, handleSubmit, formState: { errors } } = useForm({
    resolver: yupResolver(schema)
  })

  const onSubmit = (data: ResetPasswordData) => {
    setLoading(true)
    api.post('reset-password', { ...data, token: token }).then(res => {
      setLoading(false)
      return toast.current?.show({ severity: 'success', summary: 'Success Message', detail: res.data.data })
    }).catch(e => {
      setLoading(false)
      const { error, data, errors } = e.response.data
      if (error) {
        return toast.current?.show({ severity: 'error', summary: 'Error Message', detail: data })
      }
      if (errors) {
        const allErrors = Object.keys(errors).map(key => errors[key]).flat()
        return allErrors.forEach(error => toast.current?.show({ severity: 'error', summary: 'Error Message', detail: error }))
      }

      return toast.current?.show({ severity: 'error', summary: 'Error Message', detail: 'Something went wrong!' })
    })
  }

  const getFormErrorMessage = (name: string) => {
    return errors[name] && <small className="p-error">{errors[name].message}</small>
  };

  return (
    <div className="d-flex flex-grow-1">
      <Head>
        <title>Reset password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container d-flex flex-grow-1 mb-3">
        <div className="row flex-grow-1 justify-content-center align-items-center">
          <Card title='Reset password' className="col-12 col-md-9 col-lg-6 col-xl-4">
            <form onSubmit={handleSubmit(onSubmit)} className="p-fluid">
              <div className="p-field">
                <label htmlFor="email">Email</label>
                <InputText id="email" type="email" {...register("email")} />
                {getFormErrorMessage('email')}
              </div>
              <div className="p-field">
                <label htmlFor="password">Password</label>
                <InputText id="password" type="password" {...register("password")} />
                {getFormErrorMessage('password')}
              </div>
              <div className="p-field p-mb-5">
                <label htmlFor="password_confirmation">Confirm Password</label>
                <InputText id="password_confirmation" type="password" {...register("password_confirmation")} />
                {getFormErrorMessage('password_confirmation')}
              </div>
              <Button label="Submit" iconPos="right" loading={loading} />
            </form>
          </Card>
        </div>
        <Toast ref={toast} />
      </main>
    </div>
  )
}
