import Head from 'next/head'
import Image from 'next/image'
import api from '../../helpers/api'
import { GetServerSideProps } from 'next'
import Link from 'next/link'
import { useCartContext } from '../../context/cart'

// This gets called on every request
export const getServerSideProps: GetServerSideProps = async (context) => {
  const params = context.params
  let product = null
  if (params) {
    const { id } = params
    // Fetch data from external API
    const res = await api.get(`/products/${id}`)
    product = res.data.product;
  }

  // Pass data to the page via props
  return { props: { product } }
}

export default function Home(props: any) {
  const backEndUrl = process.env.NEXT_PUBLIC_BACK_END_URL
  const { addToCart } = useCartContext()
  const product = props.product;
  const discountPrice = product ? Math.round(product.price * (1 - (product.discount / 100))) : 0;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mb-3">
        <h1>Product</h1>

        {product ?
          <div className="row">
            <div className="col-12 col-lg-6">
              <Image className="w-full" src={`${backEndUrl}/storage/${product.image ? product.image : 'images/No_image_available.png'}`} alt="Mountain" width={'100%'} height={'100%'} layout='responsive' />
            </div>
            <div className="col-12 col-lg-6">
              <h1>{product.title}</h1>
              <p>{product.description}</p>
              <p>Category : {product.category}</p>
              <div className="d-flex justify-content-between mb-3">
                <div>
                  <span>Price</span>
                  <p>{`${product.price.toFixed(2)} €`}</p>
                </div>
                <div>
                  <span>Discount</span>
                  <p>{product.discount}%</p>
                </div>
                <div>
                  <span>After discount</span>
                  <p>{`${discountPrice.toFixed(2)} €`}</p>
                </div>
              </div>
              <div className="d-flex justify-content-between">
                <Link href="/"><a className="btn btn-secondary">Back</a></Link>
                <button type="button" className="btn btn-success cart" onClick={() => addToCart(product)}><i className="fa fa-shopping-cart" aria-hidden="true"></i><span className="glyphicon glyphicon-shopping-cart"></span>Add to cart</button>
              </div>
            </div>
          </div>
          :
          <div className="row">
            <h4 className="d-flex justify-content-center mt-5">There is no such product</h4>
            <div className="d-flex">
              <Link href="/"><a className="btn btn-secondary">Back</a></Link>
            </div>
          </div>
        }

      </main>
    </div >
  )
}
