import Head from 'next/head'
import Link from 'next/link'
import { logOut, useIsLoggedIn } from '../../helpers/auth'
import api from '../../helpers/api'
import { GetServerSideProps } from 'next'
import React from 'react'
import { Accordion, AccordionTab } from 'primereact/accordion';
import { CartProduct } from '../../types'

// This gets called on every request
export const getServerSideProps: GetServerSideProps = async () => {
  // Fetch data from external API
  const res = await api.get('/admin/orders')

  const orders = res.data.orders;

  // Pass data to the page via props
  return { props: { orders } }
}

export default function Orders(props: any) {
  const orders = props.orders
  const isLoggedIn: boolean = useIsLoggedIn();

  const handleLogOut = () => {
    api.post('logout').then(res => logOut())
  }

  const getDiscountPrice = (product: CartProduct) => {
    return (Math.round(product.price * (1 - (product.discount / 100)))).toFixed(2);
  }

  const getProductsPrice = (product: CartProduct) => {
    return (Math.round(product.quantity * Math.round(product.price * (1 - (product.discount / 100))))).toFixed(2);
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Link href="/cart">Cart</Link>
        {!isLoggedIn &&
          <>
            <Link href="/login">Login</Link>
            <Link href="/register">Register</Link>
          </>
        }
        {isLoggedIn &&
          <button onClick={handleLogOut}>Log out</button>
        }

      </header>

      <main className="container">
        <h1>Orders</h1>

        <div className="card">
          <Accordion multiple activeIndex={[0]}>
            {orders.map(order => (
              <AccordionTab key={order.id} header={`${order.user}  -  ${order.created_at}`}>
                <table className="table table-striped">
                  <tr>
                    <th>#</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Before Discount</th>
                    <th>Discount</th>
                    <th>After Discount</th>
                    <th>Price</th>
                  </tr>

                  {order['orderItems'].map(item => {
                    const discountPrice = getDiscountPrice(item)
                    const productsPrice = getProductsPrice(item)
                    return (
                      <tr key={item.id}>
                        <td></td>
                        <td>{item['title']}</td>
                        <td>{item['quantity']}</td>
                        <td>{item['price'] + ' €'}</td>
                        <td>{item['discount']}%</td>
                        <td>{discountPrice + ' €'}</td>
                        <td>{productsPrice + ' €'}</td>
                      </tr>
                    )
                  })}

                  <tr>
                    <td colSpan={6}>Total Price</td>
                    <td>{order['order'].total / 100 + ' €'}</td>
                  </tr>
                </table>
              </AccordionTab>
            ))}
          </Accordion>
        </div>
      </main>
    </div>
  )
}
