import Head from 'next/head'
import Link from 'next/link'
import { logOut, useIsLoggedIn } from '../../helpers/auth'
import api from '../../helpers/api'
import { GetServerSideProps } from 'next'
import React from 'react'
import { DataTable } from 'primereact/datatable'
import { Column } from 'primereact/column'

// This gets called on every request
export const getServerSideProps: GetServerSideProps = async () => {
  // Fetch data from external API
  const res = await api.get('/admin/users')

  const users = res.data.users;

  // Pass data to the page via props
  return { props: { users } }
}

export default function Categories(props: any) {
  const users = props.users
  const isLoggedIn: boolean = useIsLoggedIn();

  const handleLogOut = () => {
    api.post('logout').then(res => logOut())
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Link href="/cart">Cart</Link>
        {!isLoggedIn &&
          <>
            <Link href="/login">Login</Link>
            <Link href="/register">Register</Link>
          </>
        }
        {isLoggedIn &&
          <button onClick={handleLogOut}>Log out</button>
        }

      </header>

      <main className="container">
        <h1>Categories</h1>

        <div className="card">
          <DataTable value={users} paginator rows={15} header="Responsive">
            <Column field="name" header="Name" sortable></Column>
            <Column field="email" header="Email" sortable></Column>
            <Column field="totalOrders" header="Total orders" sortable></Column>
            <Column field="totalItems" header="Total items bought" sortable></Column>
            <Column field="totalDineros" header="Total money spent" sortable></Column>
          </DataTable>
        </div>
      </main>
    </div>
  )
}
